### ISSUE TITLE
stream and bit-shift operators probably confuse the balanced angle bracket reducer a bit

### ISSUE THREAD

**Issue by mozkeeler** [fitzgen/preduce#22]
The balanced angle bracket reducer probably does the wrong thing for things like this:
```
_ISupper = ((0) < 8 ? ((1 << (0)) << 8) : ((1 << (0)) >> 8)),                
```
or
```
basic_istream< _CharT, _Traits > &operator>>(                                    
```

**Comment by fitzgen** [comment]
I don't think we actually need to worry about this at all. Its ok to generate some false positives in reducers.

Reopen if you disagree.
