### ISSUE TITLE
Nondescript "Permission denied" error when testcase and predicate arguments are swapped

### ISSUE THREAD

**Issue by mateon1** [fitzgen/preduce#28]
In general, when the predicate is not executable, the user gets an ugly `Error: Permission denied (os error 13)`.

I had to strace the process to see preduce try to `execve()` what I passed as the testcase.

It would be great to print some user friendly message, like `Error: The provided predicate script /path/to/pred.sh could not be executed`.
That would make an error in argument order obvious. The error being `Error: The provided predicate script ./testcase.html could not be executed`.

**Comment by fitzgen** [comment]
Great idea, thanks for filing.
