### ISSUE TITLE
When nothing was reduced, preduce incorrectly reports "Final size is 0"

### ISSUE THREAD

**Issue by mateon1** [fitzgen/preduce#31]
If preduce is ran on a (non-empty) testcase, and can't reduce the file with any reducer, when preduce exits it prints `Final size is 0`.

**Comment by fitzgen** [comment]
Thanks, as always, for the bug report!

**Comment by androm3da** [comment]
https://github.com/fitzgen/preduce/pull/44 should address this problem.
