### ISSUE TITLE
Feature: binary search/chunked search for other reducers

### ISSUE THREAD

**Issue by mateon1** [fitzgen/preduce#32]
This is something on my wishlist, I may try implementing it (but I don't understand how reducers communicate with preduce yet).

Consider how `chunks.py` works - it deletes `n` consecutive lines (`lines.py`), and lowers `n` as it runs.
Imagine implementing the same chunked strategy for `blank.py`, `balanced-*.py`, `clex-rm-toks-1.py`, and possibly more.
I find that the chunked strategy is incredibly effective when most code is unrelated to the interestingness of the testcase.

Alternatively, a more proper binary search could be implemented. Consider 1 to 20 represent possible reductions in the following diagram.
A span like `\--a--/` represents that all above reductions should be tried at once, and the span is named `a`.
```
| 1| 2| 3| 4| 5| 6| 7| 8| 9|10|11|12|13|14|15|16|17|18|19|20|
 \----------------------------a----------------------------/
 \-------------b-------------/ \-------------c-------------/
 \----d-------/ \----e-------/ \----f-------/ \----g-------/
 \-h-/ \-i----/ \-j-/ \-k----/ \-l-/ \-m----/ \-n-/ \-o----/
 \/ \/ \/ \---/ \/ \/ \/ \---/ \/ \/ \/ \---/ \/ \/ \/ \---/
```
The reductions can be applied in breadth-first order (sort of like `chunks.py`), or depth-first.
The breadth-first case is easily parallelizable - try all spans in reading order when pictured as above.

The depth first algorithm would look somewhat like:
```rust
fn depth_first(span) {
  if try_reduce(span) { return; }
  let (first_half, second_half) = span.split_at(midpoint);
  depth_first(first_half);
  depth_first(second_half);
}
```

For example, say we are trying to reduce `b`.
Let's say reducing with `b` doesn't work, so we try to reduce with `d`. Say that it's successful.
Now we try reducing `e` (NOTE: Not children of `e`, as `d` could have been partially reduced). In this case it's probably unsuccessful.
Next we reduce `j` and `k` with the same strategy.

Note: This assumes the assigned spans do not change during the reduction process, which could be tricky to implement.

This is a really nice improvement for things like `blanks.py`, or (when implemented) `comments.py`, as all reductions will be first tried at once, likely successfully.

Edit:
In both binary search cases (where n is the number of possible reductions) the worst case is `2n` reduction attempts (all reductions are bad), the upper bound for the normal case is `k*log2(n)` where k is the number of single reductions that break the testcase (this is an upper bound)

**Comment by fitzgen** [comment]
See the changes to the `Reducer` trait in https://github.com/fitzgen/preduce/pull/34 as a first step in this direction.

**Comment by fitzgen** [comment]
This is done for most reducers now (everything except clang_delta and clex things) since the `reducers-next` branch merged 🎉

**Comment by fitzgen** [comment]
See https://github.com/fitzgen/preduce/blob/master/preduce_reducer_script/src/lib.rs#L273-L584
